[build]
command = "yarn build"
publish = "build/"

[build.environment]
NETLIFY_USE_YARN = "true"
NODE_VERSION = "18.18"
YARN_VERSION = "3.6.4"

[[redirects]]
force = true
from = "https://shareyourcloning.netlify.app/*"
status = 301
to = "https://shareyourcloning.org/:splat"
