name: CI / CD
on: [push, pull_request]

jobs:
  cypress-run:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install mafft
        run: |
          sudo apt-get update
          sudo apt-get install -y mafft

      - name: Download MARS executable
        run: |
          wget https://github.com/manulera/MARS/releases/download/v0.2/mars-Linux
          chmod +x mars-Linux
          sudo mv mars-Linux /usr/local/bin/mars

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install python dependencies
        run: |
          cd ShareYourCloning_backend
          poetry build
          pip install dist/shareyourcloning-*.whl

      - name: run python dev server in background
        env:
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: |
          cd ShareYourCloning_backend
          uvicorn shareyourcloning.main:app &

      - name: check if the server is running
        run: |
          for i in {1..3}; do
            if curl -s http://127.0.0.1:8000 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server... ($i/3)"
            sleep 2
          done
          echo "Server failed to start"
          exit 1

      - name: Install javascript dependencies
        run: corepack enable && yarn install

      - name: Cypress run E2E tests
        uses: cypress-io/github-action@v6
        env:
          VITE_COVERAGE: "true"
          VITE_LOG_LEVEL: "warn"
        with:
          start: yarn start
          install: false

      - name: Rename coverage file
        run: |
          mv coverage/coverage-final.json coverage-e2e.json

      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        env:
          VITE_COVERAGE: "true"
          VITE_LOG_LEVEL: "warn"
        with:
          component: true
          install: false  # Skip installation since it was done in previous step

      - name: Merge coverage reports
        run: |
          npx nyc report --reporter json --report-dir coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cypress-coverage
          path: coverage

      - name: Upload screenshots
        uses: actions/upload-artifact@v4.6.0
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/coverage-final.json

  # Update docker image when committing to master branch if tests pass
  push_to_registry:
    name: Push Docker image to Docker Hub
    # Only run if tests pass
    needs: cypress-run
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: manulera/shareyourcloningfrontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: manulera/shareyourcloningfrontend:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ github.sha }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: manulera/shareyourcloningfrontend:latest-syc-base
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_URL=/shareyourcloning/
            COMMIT_SHA=${{ github.sha }}
